/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AliadoIdRouteImport } from './routes/aliado.$id'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppExplorarRouteImport } from './routes/_app.explorar'
import { Route as AppActividadRouteImport } from './routes/_app.actividad'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AliadoIdRoute = AliadoIdRouteImport.update({
  id: '/aliado/$id',
  path: '/aliado/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorarRoute = AppExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AppRoute,
} as any)
const AppActividadRoute = AppActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividad': typeof AppActividadRoute
  '/explorar': typeof AppExplorarRoute
  '/home': typeof AppHomeRoute
  '/perfil': typeof AppPerfilRoute
  '/aliado/$id': typeof AliadoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividad': typeof AppActividadRoute
  '/explorar': typeof AppExplorarRoute
  '/home': typeof AppHomeRoute
  '/perfil': typeof AppPerfilRoute
  '/aliado/$id': typeof AliadoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/actividad': typeof AppActividadRoute
  '/_app/explorar': typeof AppExplorarRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/aliado/$id': typeof AliadoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividad'
    | '/explorar'
    | '/home'
    | '/perfil'
    | '/aliado/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/actividad' | '/explorar' | '/home' | '/perfil' | '/aliado/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/actividad'
    | '/_app/explorar'
    | '/_app/home'
    | '/_app/perfil'
    | '/aliado/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AliadoIdRoute: typeof AliadoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliado/$id': {
      id: '/aliado/$id'
      path: '/aliado/$id'
      fullPath: '/aliado/$id'
      preLoaderRoute: typeof AliadoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explorar': {
      id: '/_app/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AppExplorarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/actividad': {
      id: '/_app/actividad'
      path: '/actividad'
      fullPath: '/actividad'
      preLoaderRoute: typeof AppActividadRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActividadRoute: typeof AppActividadRoute
  AppExplorarRoute: typeof AppExplorarRoute
  AppHomeRoute: typeof AppHomeRoute
  AppPerfilRoute: typeof AppPerfilRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActividadRoute: AppActividadRoute,
  AppExplorarRoute: AppExplorarRoute,
  AppHomeRoute: AppHomeRoute,
  AppPerfilRoute: AppPerfilRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AliadoIdRoute: AliadoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
